application: mike-assignment-frontend
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /Resources
  static_dir: Resources

- url: .*
  script: index.php
